image: node:8

pipelines:
  branches:
    master:
      - step:
          script:
            - yarn
            - npm run build
            - npm run surge
  default:
    - step:
        script:
          - yarn
          - npm run build
